name: Finish Release
on:
  pull_request:
    types:
      - closed
    branches:
      - master
env:
  git_user: duplo-bot
  git_email: joe+github-bot@duplocloud.net
jobs:
  finish-release:
    if: github.event.pull_request.merged == true && (startsWith(github.head_ref, 'refs/heads/release/') || startsWith(github.head_ref, 'release/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master                 # Always finish releases from the "merged to" master
          fetch-depth: 0
          persist-credentials: false  # Needed so we can push with different credentials.
                                      # NOTE: Pushing with different credentials allows admins to push protected branches.
                                      # NOTE: Pushing with different credentials allow workflows to trigger from the push.

      # FINISH THE RELEASE
      - name: Initialize mandatory git config
        run: |
          git config --global user.name $git_user &&
          git config --global user.email $git_email
      - name: Finish gitflow release
        id: finish-release
        uses: duplocloud/ghactions-finish-gitflow-release@master
        with:
          github_token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

  version-bump:
    runs-on: ubuntu-latest
    needs:
      - finish-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      # BUMP THE DEVELOPMENT VERSION
      - name: Initialize mandatory git config
        run: |
          git config --global user.name $git_user &&
          git config --global user.email $git_email
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Version bump
        run: |
          npm version patch --no-git-tag-version &&
          git push
