name: Test
on:
  push:
env:
  duplo_host: https://prod.duplocloud.net
  duplo_tenant_id: 4b5f6dd7-c95b-4ab7-b6c6-10883941ad30
  duplo_tenant_name: gha-tests
  # user:   github-duplo-bot
  #   token:  github-duplo-cicd
  duplo_token: ${{ secrets.RELEASE_BOT_DUPLO_TOKEN }}

jobs:
  build: # make sure build/ci work properly
    name: "Build and Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run ci-commit
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    name: "Test Action Usage"
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          tenant: ${{ env.duplo_tenant_id }}
          services: |-
            [
              { "Name": "website", "Image": "nginx:latest" }
            ]
